### ISSUE TITLE
Server in 'imageRegistryCredentials' of container group should be a valid host name without protocol.

### ISSUE THREAD

**Issue by shubham1172** [Azure/aci-deploy#12]
Hello, I am trying to use this workflow to deploy my latest docker image from ACR onto ACI. I am getting the following error:

```##[error]Error: The server '$IMAGE_SERVER' in the 'imageRegistryCredentials' of container group 'somevalue-container' is invalid. It should be a valid host name without protocol.```

- The value of $IMAGE_SERVER is in the format somevalue.azurecr.io

**Comment by IslamHeggy** [comment]
Can you copy and paste your workflow file
@shubham1172

**Comment by shubham1172** [comment]
Ah, I lost the erroneous workflow file in my pool of commits! Now it's working, thanks!

**Comment by ANicholasson** [comment]
I kind off get the same error just that it says The server '' (its empty) in the 'imageRegistryCredentials' etc..

Here is my workflow file:
```yml
name: Build and deploy timekeeping app

on:
  push:
    branches: [ master ]

jobs:

  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
      
    - name: Azure authorization
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  
      
    - name: Login to private azure container registry
      uses: azure/docker-login@v1
      with:
        login-server: aronmregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push to private azure container registry
      run: |
        docker build -t aronmregistry.azurecr.io/avento-timekeeping-app:latest .
        docker push aronmregistry.azurecr.io/avento-timekeeping-app:latest
        
    - name: Deploy container to an azure container instance
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: private-docker-registry
        dns-name-label: avento-timekeeping-app
        image: aronmregistry.azurecr.io/avento-timekeeping-app:latest
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: avento-timekeeping-container
        location: 'west europe'
```
