### ISSUE TITLE
Error: The server '' (empty string) in the 'imageRegistryCredentials' of cointainer group is invalid 

### ISSUE THREAD

**Issue by ANicholasson** [Azure/aci-deploy#16]
Hi, im using this action for testing deployment from ACR to ACI and get the following error:
`Error: The server '' in the 'imageRegistryCredentials' of container group 'timekeeping-container' is invalid. It should be a valid host name without protocol.`

Here is my workflow file:
```yml
name: Build and deploy timekeeping app

on:
  push:
    branches: [ master ]

jobs:

  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
      
    - name: Azure authorization
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  
      
    - name: Login to private azure container registry
      uses: azure/docker-login@v1
      with:
        login-server: registry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push to private azure container registry
      run: |
        docker build -t registry.azurecr.io/timekeeping-app:latest .
        docker push registry.azurecr.io/timekeeping-app:latest
        
    - name: Deploy container to an azure container instance
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: docker-registry
        dns-name-label: timekeeping-app
        image: registry.azurecr.io/timekeeping-app:latest
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: timekeeping-container
        location: 'west europe'
```

**Comment by brenoalvs** [comment]
I was suffering with the same issue but I've found the solution.
You need to add the `registry-login-server` parameter also on the "Deploy" block.

```
- name: Deploy container to an azure container instance
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: docker-registry
        dns-name-label: timekeeping-app
        image: registry.azurecr.io/timekeeping-app:latest
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: timekeeping-container
        location: 'west europe'
```

Guys, please update/sync the docs between the docs site and GitHub they're very inconsistent.
