### ISSUE TITLE
Can't seem to set os-type to Windows - always throws an error

### ISSUE THREAD

**Issue by ryancole** [Azure/aci-deploy#23]
Hi folks,

I'm trying to specify the `os-type` as `Windows`. Regardless of how I specify it, it doesn't seem to satisfy the parameter. Here's my github action step ...

```yaml
      - uses: Azure/aci-deploy@v1
        with:
          name: xxx
          image: xxx.azurecr.io/xxx:${{ github.event.release.tag_name }}
          os-type: "Windows"
          location: "South Central US"
          dns-name-label: xxx
          resource-group: xxx
          registry-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          registry-login-server: xxx.azurecr.io
```

And below is the error output ...

```
Error: Error: The Value of OS Type must be either Linux or Windows only!
```
