### ISSUE TITLE
Invalid environment variable name (multiline string)

### ISSUE THREAD

**Issue by brenoalvs** [Azure/aci-deploy#29]
I'm using the workflow file below.
But I'm receiving the following error on the "Deploy to Azure Container Instances" step:

> Error: Error: The environment variable name in container 'localization-server' of container group 'localization-server' is invalid. A valid environment variable name must start with alphabetic character or `_` , followed by a string of alphanumeric characters or `_` (e.g. 'my_name',  or 'MY_NAME',  or 'MyName').

```yml
name: Azure Deployment

on: [push]

# This is to by-pass the set-env issue.
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Docker Login via Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build and push image'
    - run: |
        docker build --build-arg SSH_PRIVATE_KEY="${{ secrets.GH_SSH_PRIVATE_KEY }}" --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-org/my-app:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-org/my-app:${{ github.sha }}
     
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-org/my-app:${{ github.sha }}
        name: localization-server
        location: 'west us'
        dns-name-label: 'localization-server-${{ github.run_number }}'
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        environment-variables: TEST_ONE=testing
        secure-environment-variables: TEST_TWO=${{ secrets.ENV_TEST_TWO }}
```
