### ISSUE TITLE
Secure env vars deployed together with the plain ones as clear text

### ISSUE THREAD

**Issue by prein** [Azure/aci-deploy#47]
Not sure if I understand what is happening in the following piece:
https://github.com/Azure/aci-deploy/blob/bcb0a1ca5eb61aeb1f26a0d285bb7d62b9ce96ff/lib/taskparameters.js#L33
but it looks like the secure is mixed together with insecure?

This can also be observed if I use Terraform `azurerm_container_group` resource to deploy the same container group instance and have both `environment_variables` and `secure_environment_variables` defined in both places.

For example, if my github workflow goes like this:
```
    [...]
    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        [...]
        environment-variables: FOO = "bar"
        secure-environment-variables: BAR = "foo"
```

And my TF goes like this

resource "azurerm_container_group" "containergroup" {
```
   [...]
   container {
     [...]
     environment_variables = {
      FOO = "bar"
     }
     secure_environment_variables = {
      BAR = "foo"
     }
  }
}
```

Then terraform plan will find BAR among clear text variables 
```
          ~ environment_variables        = { # forces replacement
              - "BAR"  = "foo" -> null
            }

``` 

One can also confirm the secure env vars are stored as clear text using `az container show` or in the azure portal
Example
```
$ az container show -g my-group --name my-container | jq .containers[].environmentVariables
[
  {
    "name": "BAR",
    "secureValue": null,
    "value": "foo"
  },

```
