### ISSUE TITLE
Setting `ip-address` to `Private` causes an error

### ISSUE THREAD

**Issue by cilerler** [Azure/aci-deploy#53]
Setting below

```yaml
    - name: 'Deploy'
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        registry-login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        name: $DEPLOYMENT_NAME
        image: $IMAGE:$GITHUB_SHA
        location: 'south central us'
        os-type: Windows
        cpu: 4
        memory: 16
        environment-variables: DOTNET_ENVIRONMENT=Production
        restart-policy: OnFailure
        dns-name-label: $DEPLOYMENT_NAME
        ip-address: Private
```

throws the error below

```text
Error: DNS name label for container group is only supported when IP Address type is public.
```

and removing `dns-name-label` throws the error below

```text
Error: Input required and not supplied: dns-name-label
```
