### ISSUE TITLE
secure-environment-variables have visible values in azure portal

### ISSUE THREAD

**Issue by HonzaV** [Azure/aci-deploy#57]
Hello,
I have a security related issue with secure-environment-variables parameter of the pipeline.

I wanted to declare env secrets in pipeline, so the action would not overwrite the values setted in Container Instances in Azure Portal. Hre is my usage of the Action
 
```
- name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: backend-name
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/image-name:${{ github.sha }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: backend-name
        location: 'westeurope'
        ports: 80 8080 8070
        restart-policy: 'OnFailure'
        memory: 1
        secure-environment-variables: DB_URL="${{ secrets.DB_URL }}" DB_NAME="${{ secrets.DB_NAME }}" DB_PRIMARY_KEY="${{ secrets.DB_PRIMARY_KEY }}"
```

**Expectation**

I expected that when I look at properties of the container in azure portal I would see name of variables but not the values. 

** Reality **

There were both name and values of the properites.

**Comment by L-Sypniewski** [comment]
I'm having exactly the same problem

**Comment by sroebert** [comment]
Same problem here

**Comment by sroebert** [comment]
This seems to have been fixed in #51, but the compiled js file does not yet contain the latest changes: https://github.com/Azure/aci-deploy/blob/bcb0a1ca5eb61aeb1f26a0d285bb7d62b9ce96ff/lib/taskparameters.js

**Comment by el-pato** [comment]
@sroebert Yeah, unfortunately they need to build the the project again. There have been a number of other changes since it was last built and checked in too - and the latest "release" was almost year and a half ago.

Our solution was to clone the repository and reference that in the Github workflow file. Example:
```yaml
# Using forked aci-deploy because Microsoft isn't keeping up with official releases on the original repo
- name: 'Deploy to Azure Container Instances'
  uses: 'el-pato/aci-deploy@master'
``` 

@kanika1894 can we get recent changes built and checked in to the repo? And preferably a new release? Should we open an issue or PR for these things?

**Comment by el-pato** [comment]
@sroebert @kanika1894 actually I just saw that there is a newer release, but it's not marked as the "latest" release. https://github.com/Azure/aci-deploy/releases/tag/v1.1.2

You might be able to target that by doing something like: 
```yaml
# Using forked aci-deploy because Microsoft isn't keeping up with official releases on the original repo
- name: 'Deploy to Azure Container Instances'
  uses: 'Azure/aci-deploy@v1.1.2'
``` 

I haven't tried this yet. I will and then update here if nobody else has yet.
