### ISSUE TITLE
Multiple azure-file-volume-share-name and azure-file-volume-mount-path pairs support

### ISSUE THREAD

**Issue by NachoVazquez** [Azure/aci-deploy#62]
## The Problem

I'm trying to run a container that has multiple volumes mounts.

For example, my docker-compose would look something like:

```yml
version: '3.8'

services:
  my-container:
    image: my-container-image
    ports:
      - 3001:3001
      - 3333:3333
    environment:
      - SOME_ENV=<env-value>
    volumes:
      - vol1_host:/vol1
      - vol2_host:/vol2

volumes:
  vol1_host:
  vol2_host:

```

I've created two **Azure Storage Shares** vol1_host and vol2_host using the same **Azure Storage Account**. 

Now I need to connect my two volumes using the `aci-deploy` action, but I can not find any example of what is the syntax for multiple volumes.

How to support multiple pairs of `azure-file-volume-share-name` and `azure-file-volume-mount-path`?
