### ISSUE TITLE
Error: The api-version '2018-10-01' is invalid.

### ISSUE THREAD

**Issue by andrioid** [Azure/aci-deploy#7]
Hi there. I'm in the progress of moving my deployment from GCP to Azure, and came across an error that has me feeling pretty stuck.

I've been following [this guide](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-github-action#use-deploy-to-azure-extension), except that I'm using Github Packages instead of ACR

<details>
<summary>Error output</summary>
>Run azure/aci-deploy@v1
  with:
    resource-group: ***
    dns-name-label: ***51
    image: docker.pkg.github.com/myname/myproject/myproject-backend:aec8ca8fb1dbc8282864072b3c9b4799d0ab0fec
    registry-login-server: docker.pkg.github.com
    registry-username: myname
    registry-password: ***
    name: myproject-backend
    location: westeurope
    cpu: 1
    ip-address: Public
    memory: 1.5
    os-type: Linux
    ports: 80
    protocol: TCP
    restart-policy: Always
  env:
    PROJECT_ID: myproject-com
    RUN_REGION: europe-west1
    SERVICE_NAME: myproject-backend
    GCR_IO: eu.gcr.io
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
##[error]Error: The api-version '2018-10-01' is invalid. The supported versions are '2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
</details>

<details>
<summary>workflow.yml</summary>
```
name: Backend

on:
  push:
    branches:
      - master

jobs:
  setup-build:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to Github Packages
        uses: docker/build-push-action@v1
        with:
          path: backend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: andrioid/howbs/howbs-backend
          tags: ${{ env.GITHUB_SHA }}
          tag_with_ref: true
          tag_with_sha: true
  deployment:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: setup-build

    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Its amazing how crappy these docs are
      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.AZURE_RESOURCE_GROUP }}${{ github.run_number }}
          image: docker.pkg.github.com/andrioid/howbs/howbs-backend:${{ github.sha }}
          registry-login-server: docker.pkg.github.com
          registry-username: andrioid
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          name: howbs-backend
          location: "westeurope"
```
</details>
